import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Two sidebars: a hand-ordered usage Guide, and an API reference whose pages
 * are generated by TypeDoc into docs/api at build time (autogenerated so the
 * sidebar tracks whatever the public entry point exports).
 */
const sidebars: SidebarsConfig = {
  guide: [
    "intro",
    "getting-started",
    "how-it-works",
    {
      type: "category",
      label: "Concepts",
      collapsed: false,
      items: [
        "concepts/decisions-and-trust",
        "concepts/approvals-and-policy",
        "concepts/transitive-and-install",
        "concepts/ai-and-privacy",
        "concepts/react-native",
      ],
    },
    "cli",
    "scenarios",
    "faq",
  ],
  api: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
