import { existsSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { proxyStateDir } from "./proxy-daemon.js";

/**
 * Environment-based routing for the proxy. targate never edits a project's
 * committed `.npmrc`; instead it points package managers at the proxy through
 * environment variables (see the vulnerability/proxy design). The registry keys
 * differ per manager:
 *   - npm  → `npm_config_registry` / `NPM_CONFIG_REGISTRY`
 *   - pnpm → `npm_config_registry` (honored at install time)
 *   - yarn berry → `YARN_NPM_REGISTRY_SERVER`
 *
 * Two shapes:
 *   - `sourceableEnvLines` — `export KEY="val"` lines for `~/.targate/proxy.env`,
 *     which the user sources. Only shell-identifier-safe names (the default
 *     registry + the CA), so it covers PUBLIC installs on all three managers.
 *   - `execEnv` — a full env map for `targate proxy exec`, which spawns a command
 *     directly. A child env (unlike `export`) may contain keys with `@` and `:`,
 *     so exec ALSO sets the per-scope override `npm_config_@scope:registry` that
 *     a sourced file cannot express — the only transparent way to gate a private
 *     scope pinned in a committed `.npmrc` on npm/pnpm.
 */

export interface ProxyEnvInputs {
  /** The proxy registry origin, e.g. https://127.0.0.1:4873 */
  registryUrl: string;
  /** Absolute path to the local CA (for NODE_EXTRA_CA_CERTS). */
  caPath: string;
  /** Private scopes to route through the proxy (e.g. ["@acme"]). */
  scopes?: string[];
}

export function proxyEnvPath(): string {
  return path.join(proxyStateDir(), "proxy.env");
}

/** Identifier-safe env pairs (default registry for every manager + the CA). */
function baseEnv(inputs: ProxyEnvInputs): Record<string, string> {
  return {
    npm_config_registry: inputs.registryUrl, // npm + pnpm
    NPM_CONFIG_REGISTRY: inputs.registryUrl, // npm (redundant, maximally compatible)
    YARN_NPM_REGISTRY_SERVER: inputs.registryUrl, // yarn berry
    NODE_EXTRA_CA_CERTS: inputs.caPath,
  };
}

/** Normalize a scope to yarn berry's env segment: `@acme-co` -> `ACME_CO`. */
function berryScopeSegment(scope: string): string {
  return scope.replace(/^@/, "").toUpperCase().replace(/[^A-Z0-9]/g, "_");
}

/** `export KEY="val"` lines for the sourceable proxy.env (public routing). */
export function sourceableEnvLines(inputs: ProxyEnvInputs): string[] {
  const env = baseEnv(inputs);
  const lines = [
    "# targate proxy — source this to route installs through the local vetting proxy.",
    "# Machine-local, regenerated by `targate proxy setup`. Do not commit; it is not a repo file.",
    "# Gates PUBLIC installs (npm/pnpm/yarn-berry). For a private scope pinned in a",
    "# committed .npmrc on npm/pnpm, use: targate proxy exec -- <your install command>.",
  ];
  for (const [key, value] of Object.entries(env)) {
    lines.push(`export ${key}="${value}"`);
  }
  return lines;
}

export function writeProxyEnvFile(inputs: ProxyEnvInputs): string {
  const file = proxyEnvPath();
  writeFileSync(file, sourceableEnvLines(inputs).join("\n") + "\n");
  return file;
}

export function removeProxyEnvFile(): void {
  const file = proxyEnvPath();
  if (existsSync(file)) rmSync(file, { force: true });
}

/**
 * The full environment for `targate proxy exec`: the base routing plus per-scope
 * overrides that gate a private scope even when it is pinned in a committed
 * `.npmrc`. `npm_config_@scope:registry` cannot be `export`ed from a shell (not a
 * valid identifier) but is a valid child-process env key, so exec is the way to
 * apply it. A best-effort yarn-berry per-scope override is included too.
 */
export function execEnv(base: NodeJS.ProcessEnv, inputs: ProxyEnvInputs): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...base, ...baseEnv(inputs) };
  for (const scope of inputs.scopes ?? []) {
    env[`npm_config_${scope}:registry`] = inputs.registryUrl; // npm + pnpm
    env[`YARN_NPM_SCOPES_${berryScopeSegment(scope)}_NPM_REGISTRY_SERVER`] = inputs.registryUrl; // berry (best-effort)
  }
  return env;
}
